# Site wide configuration

title:            hochulshin.com
locale:           en_US
url: 


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: false
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Hochul Shin
  avatar: avatar.jpg
  bio: "Software engineer specialized in distributed systems and multimedia"
  email:
  disqus-shortname: dakoogithubio
  twitter: #username
  facebook: hochul.shin0
  google:
    plus: #username
    analytics: UA-60163348-2  
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: dakoo
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: hochulshin0
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
